Calico lab exercise
Azure/kubernetes-hackfest pull request #237
Opened 2021-08-11 20:04 UTC by jessieziyuantang

Add calico lab exercise with some open-source features.

2021-08-24 14:51 UTC, swgriffith requested changes
Hey Jessie,

Thanks for the PR! I added a bunch of comments. Content overall looks great and works well.

2021-08-24 14:51 UTC, swgriffith commented on labs/networking/calico-lab-exercise/modules/using-observability-tools.md
> +
Should add a note here that users can select which cluster they're looking at via the drop down in the upper right corner of the portal. They may end up seeing the default management cluster which can be confusing.

2021-08-24 14:51 UTC, swgriffith commented on labs/networking/calico-lab-exercise/modules/using-observability-tools.md
> +    # try to ping any of the IPs in from the feodo tracker list, and the packet will be deny.
'packet will be denied'

2021-08-24 14:51 UTC, swgriffith commented on labs/networking/calico-lab-exercise/modules/using-observability-tools.md
> +    kubectl -n dev exec -t centos -- sh -c 'curl -m3 -skI https://www.azure.com 2>/dev/null | grep -i http'
Not critical, but it may be good to swap out *.azure.com with *.microsoft.com or *.tigera.io, since azure.com is an HTTP 301. Might confuse some people.

2021-08-24 14:51 UTC, swgriffith commented on labs/networking/calico-lab-exercise/modules/anomaly-detection.md
> +
Might be good to have people verify the change was applied correctly with something like the following:

cat demo/90-anomaly-detection/ad-jobs-deployment-managed.yaml |grep -B 5 -A 5 $CALICOCLUSTERNAME

2021-08-25 13:33 UTC, swgriffith commented on labs/networking/calico-lab-exercise/README.md
> +- [Calico Cloud trial account](https://www.calicocloud.io/home)
Btw - If this isnt something you all want to do, I'll likely modify our existing AKS Azure Network Policy lab to use Calico, just as a backup for users that just want to do a 5-10min network policy walk through vs. the full calico workshop content. Then at the end of that very basic lab I can reference this content.

2021-08-25 13:34 UTC, swgriffith commented on labs/networking/calico-lab-exercise/modules/packet-capture.md
> +    tcpdump -Xr frontend-XXXXXX.pcap
To run it locally, as we ran through in the last workshop, users can use the Azure Cloud Shell 'download' command to pull the pcap locally and then open with Wireshark or tcpdump.

2021-08-25 14:45 UTC, raykao commented on labs/networking/calico-lab-exercise/README.md
> +    az aks delete --name $CLUSTERNAME
needs to include the name of the Resource Group to delete the cluster successfully

`az aks delete --name $CLUSTERNAME --resource-group $RGNAME`

2021-08-31 15:04 UTC, swgriffith commented on labs/networking/calico-lab-exercise/README.md
> +[Calico User Group Slack](https://slack.projectcalico.org/) is a great resource to ask any questions about Calico. If you are not a part of this Slack group yet, we highly recommend [joining it](http
I'm still seeing 'EKS' in the following sentence.

'For example, you can ask questions specific to **EKS** and other managed Kubernetes services in the #eks-aks-gke-iks channel'

2021-09-13 19:24 UTC, merged